### ISSUE TITLE
Mainactivity.java Code Refactoring 요청

### ISSUE THREAD

**Issue by destiny3912** [destiny3912/TourToKorea#16]
GPS 관련한 메서드 제거 관련해서 Code Refactoring 요청드립니다.

**Comment by WaGaNaWa-EingEing** [comment]
onCreate 메소드 내부에서

if (checkLocationServicesStatus()) {
            checkRunTimePermission();
        } else {
            showDialogForLocationServiceSetting();
        }

를 통해 호출한 메소드 내부 절차에서 GPS 권한을 확인하고 이를 요청하는 처리를 실행하고 있으며 이걸 Main activity에 넣어 처리해둔 사유는 길찾기, 길안내, 위치정보 각 3가지 액티비티에서 상황에 따라 gps 위치를 사용할수 있도록 설계되어 있는데 이떄마다 GPS 권한을 확인하여 재요청하기보다 app이 시작하는 가장 첫 액티비티단에서 gps 권한을 허용받을수 있도록 하기위해 Mainactivity.java 의 onCreate 단계에서 이 메소드를 호출한 것이며. 

별도의 버튼 관련한 함수는 액티비티를 호출하는 호출예제를 보이기 위해 작성한 코드이나 
저 GPS 권한 확인 관련한 메소드는 앱 첫 실행시 반드시 실행되어야 하는 메소드이기에 기본적으로 제거보단 관련 메소드 전체를 app의 시작 액티비티 내부에 이동시켜 줘야합니다.

**Comment by destiny3912** [comment]
확인했습니다
